class Images {
//  PNG Pick

  static String loginb = 'images/loginb.png';
  static String google = 'images/google.png';
  static String apple = 'images/apple.svg';
  static String window = 'images/window.png';
  static String Rectangleprson = 'images/Rectangleprson.png';
  static String Linep = 'images/Linep.png';
  static String graysta = 'images/graystar.png';
  static String bluestar = 'images/blue.png';

  static String Emoji4 = 'images/Emoji4.png';
  static String Emoji6 = 'images/Emoji6.png';
  static String Emoji7 = 'images/Emoji7.png';
  static String Emoji8 = 'images/Emoji8.png';
  static String Emoji9 = 'images/Emoji9.png';
  static String Emoji10 = 'images/Emoji10.png';
  static String Emoji11 = 'images/Emoji11.png';
  static String Emoji12 = 'images/Emoji12.png';
  static String Emoji13 = 'images/Emoji13.png';
  static String Emoji14 = 'images/Emoji14.png';
  static String Emoji15 = 'images/Emoji15.png';

  static String Emoji5 = 'images/Emoji5.png';
  static String collectionist = 'images/collectionist.png';
  static String Reach2 = 'images/Reach2.png';
  static String Market3 = 'images/Market3.png';
  static String Livello9copia = 'images/Livello9copia.png';

  static String badges1 = 'images/badges1.png';
  static String badges2 = 'images/badges2.png';
  static String badges3 = 'images/badges3.png';
  static String badges4 = 'images/badges4.png';
  static String badges5 = 'images/badges5.png';
  static String badges6 = 'images/badges6.png';
  static String sallerProfile = 'images/sallerProfile.png';
  static String madel = 'images/madel.png';
  static String Bronze = 'images/Bronze.png';
  // static String google = 'images/google.svg';

  // static String google = 'images/google.svg';

//  Svg Pick

  static String homefil = 'images/homefill.svg';
  static String searchfil = 'images/searchfill.svg';
  static String likefil = 'images/likefil.svg';
  static String commentfill = 'images/commentfill.svg';
  static String homeicon = 'images/homeicon.svg';
  static String searchIcon = 'images/searchIcon.svg';
  static String comment = 'images/commenticon.svg';
  static String profileicon = 'images/profileicon.svg';
  static String likeicon = 'images/likeicon.svg';
  static String notification = 'images/notification.svg';
  static String reelicon = 'images/reelicon.svg';
  static String like = 'images/like.svg';
  static String coment = 'images/comenty.svg';
  static String share = 'images/share.svg';
  static String threedot = 'images/threedot.svg';

  static String interface = 'images/interface.svg';
  static String expanddiamond = 'images/expanddiamond 1.svg';
  static String moneycredit = 'images/money-credit.svg';
  static String BS = 'images/BS.svg';
  static String shoppinggift = 'images/shopping-gift.svg';
  static String usersswitc = 'images/users-switch.svg';
  static String jaha = 'images/jahaz.svg';
  static String usersidentifier = 'images/users-identifier.svg'; // 2 time
  static String setting = 'images/setting.svg';
  static String person = 'images/person.svg';
  static String Vector = 'images/Vector.svg';
  static String Line = 'images/Line.svg';
  static String Heart = 'images/Heart.svg';
  static String Send = 'images/Send.svg';
  static String comments = 'images/comment.svg';
  static String ms = 'images/ms.svg';
  static String emoje = 'images/emoje.svg';
  static String notilines = 'images/notilines.svg';
  static String vice = 'images/vice.svg';
  static String box = 'images/box.svg';
  static String camera = 'images/camera.svg';
  static String stepline = 'images/stepline.svg';
  static String circular = 'images/circular.svg'; // status Circular
  static String one = 'images/one.svg';
  static String two = 'images/two.svg';
  static String three = 'images/three.svg';
  static String boldcircular = 'images/boldcircular.svg';
  static String containergr = 'images/containergr.svg'; //
  static String smile = 'images/smile.svg';
  static String Sendto = 'images/Sendto.svg';
  static String Chat = 'images/Chat.svg';
  static String PK = 'images/PK.svg';
  static String AF = 'images/AF.svg';
  static String IN = 'images/IN.svg';
  static String IT = 'images/IT.svg';
  static String Filteralt = 'images/Filter alt.svg';
  static String Danger = 'images/Danger.svg';
  static String tudoom1 = 'images/tudoom1.svg';
  static String tudoom2 = 'images/tudoom2.svg';
  static String tudoom3 = 'images/tudoom3.svg';
  static String tudoom4 = 'images/tudoom4.svg';
  static String tudoom5 = 'images/tudoom5.svg';
  static String tudoom6 = 'images/tudoom6.svg';
  static String tudoom7 = 'images/tudoom7.svg';
  static String tudoom8 = 'images/tudoom8.svg';
  static String searchPerson = 'images/searchPerson.png';
  static String Account = 'images/Account.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';
  // static String one = 'images/one.svg';

// Local  Pic

  static String home1 = 'images/local/home1.png';
  static String home2 = 'images/local/home2.png';
  static String home3 = 'images/local/home3.png';
  static String home4 = 'images/local/home4.png';
  static String home5 = 'images/local/home5.png';
  static String post = 'images/local/post.png';
  static String profile = 'images/local/profile.png';
  static String post1 = 'images/local/post1.png';
  static String post2 = 'images/local/post2.png';
  static String post3 = 'images/local/post3.png';
  static String post4 = 'images/local/post4.png';
  static String post5 = 'images/local/post5.png';

  static String chat1 = 'images/chat1.png';
  static String chat2 = 'images/local/chat2.png';
  static String chat3 = 'images/local/chat3.png';
  static String cjhat4 = 'images/local/cjhat4.png';
  static String chat5 = 'images/local/chat5.png';
  static String chat6 = 'images/local/chat6.png';
  static String room1 = 'images/local/room1.png';
  static String room2 = 'images/local/room2.png';
  static String room3 = 'images/local/room3.png';
  static String room4 = 'images/local/room4.png';
  static String local = 'images/local/local.png';
  static String aa = 'images/local/aaa.png';
  static String firend1 = 'images/local/firend1.png';
  static String firend2 = 'images/local/firend2.png';
  static String firend3 = 'images/local/firend3.png';
  static String firend4 = 'images/local/firend4.png';
  static String firend5 = 'images/local/firend5.png';
  static String patispat = 'images/local/patispat.png';
  static String Participant1 = 'images/local/Participant1.png';
  static String Participant2 = 'images/local/Participant2.png';
  static String Participant3 = 'images/local/Participant3.png';
  static String Participant4 = 'images/local/Participant4.png';
  static String Participant5 = 'images/local/Participant5.png';
  static String Participant = 'images/local/Participant6.png';
  static String hompatispa2 = 'images/local/patispa22.png';
  static String hometext = 'images/local/hometext.png';
  static String reffrals1 = 'images/local/reffrals1.png';
  static String reffrals2 = 'images/local/reffrals2.png';
  static String reffrals3 = 'images/local/reffrals3.png';
  static String reffrals4 = 'images/local/reffrals4.png';
  static String onlinepic = 'images/local/onlinepic.png';
  // static String home1 = 'images/local/home1.png';
  // static String home1 = 'images/local/home1.png';
  // static String home1 = 'images/local/home1.png';
  // static String home1 = 'images/local/home1.png';
  // static String home1 = 'images/local/home1.png';
  // static String home1 = 'images/local/home1.png';
  // static String home1 = 'images/local/home1.png';
  // static String home1 = 'images/local/home1.png';
  // static String home1 = 'images/local/home1.png';
  // static String home1 = 'images/local/home1.png';
  // static String home1 = 'images/local/home1.png';
}
